/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function deviceName(): string

export declare function evalGraph(graphJson: string, leaves: Float32Array, seed: number): Readback

/**
 * Evaluate a plan: overlay the dirty leaves (packed in increasing leaf
 * index, listed by `dirty_index`) onto the pins, then run. JS callers
 * are single-threaded, so holding the handle lock through the
 * evaluation cannot deadlock; rayon workers never touch the handle map.
 */
export declare function evalPrepared(handle: number, dirty: Float32Array, dirtyIndex: Uint32Array, seed: number): Readback

/** Copy a leaf's current values into the handle's pinned buffer. */
export declare function pinLeaf(handle: number, leaf: number, data: Float32Array): void

/**
 * How many prepared-graph handles are currently held. Used by tests to
 * assert that `releaseGraph` / compiled `dispose()` actually frees them.
 */
export declare function preparedGraphCount(): number

/** Parse and plan a graph once, returning a handle for `evalPrepared`. */
export declare function prepareGraph(graphJson: string): number

/** Drop a plan created by `prepareGraph`. */
export declare function releaseGraph(handle: number): void

/**
 * Row-major C = A·B for one packed f32 pair — the eager fast path's
 * escape hatch into Accelerate. Same `gemm` the loop evaluator uses.
 */
export declare function sgemm(a: Float32Array, b: Float32Array, m: number, k: number, n: number): Readback

/** Op-kind timings gathered since the last call, as a text table. */
export declare function takeProfile(): string
